[project]
name = "blogs-api"
version = "0.1.0"
description = "A template project for future blogs API"
readme = "README.md"
authors = [
    { name = "clipklop", email = "" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard,standart]>=0.141.1",
]

[project.scripts]
blogs-api = "blogs_api.main:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
