from collections.abc import Generator

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

from blogs_api.config import settings


database_url = make_url(settings.database_url)
postgresql_engine_options = {}
if database_url.get_backend_name() == "postgresql":
    postgresql_engine_options = {
        # Maximum time spent establishing a new PostgreSQL connection.
        "connect_args": {"connect_timeout": settings.database_connect_timeout},
        # Maximum time spent waiting for a pooled connection.
        "pool_timeout": settings.database_pool_timeout,
    }

engine = create_engine(
    database_url,
    pool_pre_ping=True,    # checks if the connection is alive before using it, to help PostgreSQL after restarts
    echo=settings.sql_echo,    # for debugging, logs all SQL statements generated by SQLAlchemy
    **postgresql_engine_options,
)

SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    expire_on_commit=False,
)


class Base(DeclarativeBase):
    pass


def get_db() -> Generator[Session, None, None]:
    with SessionLocal() as session:
        yield session
