from collections.abc import Generator

from pydantic_settings import BaseSettings, SettingsConfigDict
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker


class Settings(BaseSettings):
    database_url: str
    sql_echo: bool = False
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        # env_prefix="BLOGS_",
        extra="ignore",
    )

settings = Settings()

engine = create_engine(
    settings.database_url, 
    pool_pre_ping=True,    # checks if the connection is alive before using it, to help PostgreSQL after restarts
    echo=settings.sql_echo    # for debugging, logs all SQL statements generated by SQLAlchemy
)

SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    expire_on_commit=False,
)


class Base(DeclarativeBase):
    pass


def get_db() -> Generator[Session, None, None]:
    with SessionLocal() as session:
        yield session
